apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: web	
  template:
   metadata:
    labels:
      component: web
   spec:
    containers:
    - name: k8sdemo
      image: kishanaduka/k8s-demo
      ports:
       - containerPort: 8080
      
    
       
